apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: vspheremachineproviderstatuses.vsphereproviderconfig.sigs.k8s.io
spec:
  group: vsphereproviderconfig.sigs.k8s.io
  names:
    kind: VsphereMachineProviderStatus
    plural: vspheremachineproviderstatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        networkStatus:
          description: Network returns the network status for each of the machine's
            configured network interfaces.
          items:
            properties:
              connected:
                description: Connected is a flag that indicates whether this network
                  is currently connected to the VM.
                type: boolean
              ipAddrs:
                description: IPAddrs is one or more IP addresses reported by vm-tools.
                items:
                  type: string
                type: array
              macAddr:
                description: MACAddr is the MAC address of the network device.
                type: string
              networkName:
                description: NetworkName is the name of the network.
                type: string
            required:
            - macAddr
            type: object
          type: array
        taskRef:
          description: TaskRef is a managed object reference to a Task related to
            the machine.
          type: string
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
